name: Auto Merge and Label PRs

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [closed]

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Obter número do PR
        id: get_pr_number
        run: echo "PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

      - name: Fazer merge automático do PR aprovado (squash)
        if: github.event.review.state == 'approved'
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}/merge" \
          -d '{"merge_method":"squash"}'

  manage_labels:
    needs: auto_merge
    runs-on: ubuntu-latest
    steps:
      - name: Obter PRs fechados com labels de faixa
        id: get-merged-prs
        run: |
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=closed&labels=Faixa*")
          PR_COUNT=$(echo "$RESPONSE" | jq length)
          CURRENT_FAIXA=$((PR_COUNT / 10 + 1))
          echo "NEXT_FAIXA=Faixa $CURRENT_FAIXA" >> $GITHUB_ENV

      - name: Criar label da faixa caso não exista
        run: |
          LABEL_EXISTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/labels" | jq -r ".[] | select(.name == \"${{ env.NEXT_FAIXA }}\") | .name")

          if [ -z "$LABEL_EXISTS" ]; then
            curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/labels" \
              -d "{\"name\": \"${{ env.NEXT_FAIXA }}\", \"color\": \"0075ca\"}"
          fi

      - name: Adicionar label ao PR mergeado
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "${{ env.NEXT_FAIXA }}"
